server:
 port: 9292

spring:
 sql:
  init:
   mode: always
   continue-on-error: true
 data:
  jpa:
   repositories:
    enabled: true
 datasource:
     driverClassName: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/postgres
     username: postgres
     password: 1234
